In [3]:
import numpy as np
import pandas as pd

In [4]:
ratings_data = {
    'user': [0, 0, 1, 1, 2, 3, 4, 4, 5, 6, 7, 7, 8, 8, 9, 9],
    'item': [0, 1, 0, 2, 2, 1, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2],
    'rating': [4, 5, 5, 3, 2, 4, 4, 2, 5, 4, 3, 2, 5, 4, 4, 5]
}

ratings = pd.DataFrame(ratings_data)
ratings.head()

user  item  rating
0     0     0       4
1     0     1       5
2     1     0       5
3     1     2       3
4     2     2       2

In [5]:
trust_data = {
    'user': [0, 1, 1, 2, 3, 4, 5, 6, 7, 8],
    'trusted_user': [1, 0, 2, 3, 4, 5, 6, 7, 8, 9]
}

trust = pd.DataFrame(trust_data)
trust.head()

user  trusted_user
0     0             1
1     1             0
2     1             2
3     2             3
4     3             4

In [6]:
num_users = ratings['user'].nunique()
num_items = ratings['item'].nunique()
print(f"Number of users: {num_users}")
print(f"Number of items: {num_items}")

Number of users: 10
Number of items: 5


In [7]:
R = np.zeros((num_users, num_items))

for row in ratings.itertuples():
    R[row.user, row.item] = row.rating

print("User-Item Ratings Matrix (R):")
print(R)


User-Item Ratings Matrix (R):
[[4. 5. 0. 0. 0.]
 [5. 0. 3. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 4. 0. 0. 0.]
 [0. 0. 0. 4. 2.]
 [5. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0.]
 [0. 0. 3. 2. 0.]
 [4. 0. 0. 0. 5.]
 [0. 4. 5. 0. 0.]]


In [8]:
trust_matrix = np.zeros((num_users, num_users))
for row in trust.itertuples():
    trust_matrix[row.user, row.trusted_user] = 1

print("Trust Matrix:")
print(trust_matrix)


Trust Matrix:
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [9]:
def predict_rating_trust(target_user, target_item):
    trusted_users = np.where(trust_matrix[target_user] == 1)[0]

    trusted_ratings = []
    for u in trusted_users:
        rating = R[u, target_item]
        if rating > 0:
            trusted_ratings.append(rating)

    if len(trusted_ratings) == 0:
        user_ratings = R[target_user]
        rated_items = user_ratings[user_ratings > 0]
        if len(rated_items) > 0:
            return np.mean(rated_items)
        else:
            return 0

    return np.mean(trusted_ratings)

In [10]:
sample_user = 1

for item in range(num_items):
    predicted_rating = predict_rating_trust(sample_user, item)
    print(f"Predicted rating for user {sample_user} on item {item}: {predicted_rating:.2f}")


Predicted rating for user 1 on item 0: 4.00
Predicted rating for user 1 on item 1: 5.00
Predicted rating for user 1 on item 2: 2.00
Predicted rating for user 1 on item 3: 4.00
Predicted rating for user 1 on item 4: 4.00
